version: '3.8'
services:
  postgres_db:
    image: postgres:16.1-alpine3.19
    networks:
      - database
    env_file: ./backend/.env
    restart: always
    expose:
      - 5432
    volumes:
      - ./database/prod:/var/lib/postgresql/data
    container_name: postgres_db
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - database
    env_file: ./backend/.env
    ports:
      - 3000:3000
    depends_on:
      - postgres_db
    container_name: backend
  frontend:
    build:
      context: ./frontend
      target: production
      dockerfile: Dockerfile
    env_file: ./frontend/.env
    depends_on:
      - backend
    ports:
      - 8000:8000
    container_name: frontend

networks:
  database:
    name: database
    driver: bridge